/*
 * This source file was generated by the Gradle 'init' task
 */
package Smithson.WaterEnergyCalculator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
} 

// References:
/* 
 * GeeksforGeeks – Java program to convert Fahrenheit into Celsius 
 *     https://www.geeksforgeeks.org/java/java-program-to-convert-fahrenheit-into-celsius/
 *
 * JDoodle – Online compiler and editor for Java, C/C++, etc. 
 *     https://www.jdoodle.com/online-java-compiler
 *
 * Liang, Y. Daniel – Introduction to Java Programming and Data Structures, 13th Edition 
 *     Pearson Lifetime eBooks. ISBN: 9780138123352
 *
 * OpenAI ChatGPT – Used for code review and documentation guidance
 */