/*
 * This source file was generated by the Gradle 'init' task
 * Asher Smithson
 * September 18, 2025
 * M2 Programming Assignment
 */
// This program calculates the energy needed to heat water based on mass and temperature change with water
// per a specified amount of water from an intial temperature to a final temperature.
// Water is measured in kilograms and temperature is measured in celcius.
package Smithson.WaterEnergyCalculator;

import java.util.Scanner;

public class App{
    public static void main(String[] args) {
        final double SPECIFIC_HEAT = 4184.0; // specific heat capacity of water (J/kg.°C)
        
        Scanner input = new Scanner(System.in);
        
        // Asking the user for the mass of the water in kilograms
        System.out.print("Enter the amount of water in kilograms: ");
        double waterMass = input.nextDouble();
        
        // Asking the user for the initial temperature in Celsius
        System.out.print("Enter the initial temperature (°C): ");
        double initialTemperature = input.nextDouble();
        
        // Asking the user for the final temperature in Celsius
        System.out.print("Enter the final temperature (°C): ");
        double finalTemperature = input.nextDouble();
        
        // Calculate the required energy by water mass * (finalTemp - initial Temp) * specific heat constant
        double energyNeeded = waterMass * (finalTemperature - initialTemperature) * SPECIFIC_HEAT;
        
        //Display the result to the user with two decimal places
        System.out.printf("The energy needed is %.2f Joules.%n", energyNeeded);
        
        // Scanner needs to close to release resources
        input.close();
    }
}
// References
/*
 * GeeksforGeeks – Java program to convert Fahrenheit into Celsius 
 *     https://www.geeksforgeeks.org/java/java-program-to-convert-fahrenheit-into-celsius/
 *
 * JDoodle – Online compiler and editor for Java, C/C++, etc. 
 *     https://www.jdoodle.com/online-java-compiler
 *
 * Liang, Y. Daniel – Introduction to Java Programming and Data Structures, 13th Edition 
 *     Pearson Lifetime eBooks. ISBN: 9780138123352
 *
 * OpenAI ChatGPT – Used for code review and documentation guidance
 */